{
 "title": "Netology",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Mem Free/Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_memory_MemFree_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"})",
     "legendFormat": "MemFree"
    },
    {
     "expr": "avg(node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"})",
     "legendFormat": "MemAvailable"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=\"ext4\",instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "Free in {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype=\"ext4\",instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "Total in {{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance)(rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[$__rate_interval])) * 100"
    }
   ]
  },
  {
   "title": "CPU Load average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load1{}[$__rate_interval]))",
     "legendFormat": "LA1"
    },
    {
     "expr": "avg by (instance)(rate(node_load5{}[$__rate_interval]))",
     "legendFormat": "LA5"
    },
    {
     "expr": "avg by (instance)(rate(node_load15{}[$__rate_interval]))",
     "legendFormat": "LA15"
    }
   ]
  }
 ]
}