---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: ssh
      ansible_host: 192.168.56.10
      ansible_ssh_pass: paswd123
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

